name: Megaton Records
favicon: null
layout_spectrum: 0.037226386135444045
typography_spectrum: 0.27654974488541484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9369122397620231
  lightness: 0.47155477246269584
  saturation: 0.16647446784190834
  rhythmicContrast: 0.6449290849268436
purpose: []
